version: '2'
services:
    koulusafkaapi-app:
        image: koulusafkaapi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://koulusafkaapi-mysql:3306/koulusafkaapi?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    koulusafkaapi-mysql:
        extends:
            file: mysql.yml
            service: koulusafkaapi-mysql
